rework gitlab-ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -65,10 +65,23 @@ deploy:
         sleep 3
       done
       
-      docker-compose -f docker-compose.backend.yml up -d nginx
+      for attempt in {1..5}; do
+        echo "Attempt $attempt to start nginx"
+        docker-compose -f docker-compose.backend.yml up -d nginx
+        sleep 10  # Даем время на старт
+      
+        if docker ps --filter "name=lootor_nginx" --format "{{.Status}}" | grep -q "Up"; then
+          echo "Nginx is up and running"
+          break
+        else
+          echo "Nginx failed to start, retrying..."
+          docker-compose -f docker-compose.backend.yml stop nginx || true
+        fi
+      done
       
       docker-compose -f docker-compose.backend.yml ps
       docker logs lootor_backend1 --tail 50
       docker logs lootor_auc --tail 20
+      docker logs lootor_nginx --tail 20 || true
       exit
       EOF
