kaniko for prod

diff --git a/.gitlab-ci-dev.yml b/.gitlab-ci-dev.yml
--- a/.gitlab-ci-dev.yml
+++ b/.gitlab-ci-dev.yml
@@ -87,7 +87,11 @@ deploy:
       fi
       
       docker-compose -f docker-compose.backend.yml stop backend
-      docker-compose -f docker-compose.backend.yml pull backend
+      docker pull ${CI_REGISTRY_IMAGE}:latest || {
+      echo "ERROR: Pull failed for ${CI_REGISTRY_IMAGE}:latest";
+      docker inspect ${CI_REGISTRY_IMAGE}:latest || true;
+      exit 1;
+      }
       docker-compose -f docker-compose.backend.yml up -d backend
       
       for i in {1..15}; do
