kaniko for prod

diff --git a/.gitlab-ci-dev.yml b/.gitlab-ci-dev.yml
--- a/.gitlab-ci-dev.yml
+++ b/.gitlab-ci-dev.yml
@@ -57,7 +57,10 @@ deploy:
     - echo "=================deploy to host================="
     - |
       ssh -o StrictHostKeyChecking=no -t -t root@185.43.4.23 << EOF  # DEV хост
-      docker login -u gitlab-ci-token -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
+      docker login -u "$CI_DEPLOY_USERNAME" -p "$CI_DEPLOY_PASSWORD" registry.gitlab.com || {
+        echo "ERROR: Docker login failed";
+        exit 1;
+      }
       docker pull ${CI_REGISTRY_IMAGE}:latest
       cd ../lootor
       
@@ -87,10 +90,7 @@ deploy:
       fi
       
       docker-compose -f docker-compose.backend.yml stop backend
-      docker login -u "$CI_DEPLOY_USERNAME" -p "$CI_DEPLOY_PASSWORD" registry.gitlab.com || {
-        echo "ERROR: Docker login failed";
-        exit 1;
-      }
+      docker-compose -f docker-compose.backend.yml pull backend
       docker-compose -f docker-compose.backend.yml up -d backend
       
       for i in {1..15}; do
